# Generated by Django 5.1 on 2024-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
